[shell]
program = 'wsl ~'

[keyboard]
bindings = [
	{key = "Space", mods = "Control", chars = "\u0000"},
]

[font]
normal = { family = "Hack Nerd Font Mono" }
size = 12

[keyboard]
bindings = [
  { key = "Enter", mods = "Control", action = "CreateNewWindow" }
]
